@host=https://localhost:7283

GET {{host}}/properties/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOWNjZDIwNy02ZDFlLTQ4ZjgtYjdkZi0zNTY1YjRiM2U5NjciLCJnaXZlbl9uYW1lIjoiVG9tIiwiZmFtaWx5X25hbWUiOiJGZWx0b24iLCJqdGkiOiJkNTA0YTBjYi0zYzcyLTRiYmQtOTdmMy0yZDAxODExMDkwY2YiLCJleHAiOjE3MTg1NTM1MDIsImlzcyI6IlJlYWx0b3JUZXN0MSIsImF1ZCI6IlJlYWx0b3JUZXN0MV9Vc2VycyJ9.p1arAYMr3dPb4QH6sCGody03YSYPaFWp_-ucnUDEKac

# Content-Type: application/json

# {
#   "id": 5,
#   "description": "3 BHK Condo",
#   "type": "Residential",
#   "address": "102 Heaven St.",
#   "address2": "",
#   "city": "Calgary",
#   "region": "Alberta",
#   "postalCode": "A989B3",
#   "country": "Canada",
#   "phone": "9876543214"
# }