@host=https://localhost:7283

POST {{host}}/properties/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMDRlZjI4NC1jMzY4LTQ1NmItYTVkNC0wOWJhNGYwOTY1ODYiLCJnaXZlbl9uYW1lIjoiVG9tIiwiZmFtaWx5X25hbWUiOiJGZWx0b24iLCJqdGkiOiI5MTlkNDkxNy00NTIyLTQ4YWUtOTNlMS05OTllZTYwY2MxOGIiLCJleHAiOjE3MjAzNjE2MTAsImlzcyI6IlJlYWx0b3JUZXN0MSIsImF1ZCI6IlJlYWx0b3JUZXN0MV9Vc2VycyJ9.KOhtpBA9jmBdNfefARUj_zeh8zx8Kj_yJJOcJutqf14
Content-Type: application/json

{
  "id": 5,
  "description": "3 BHK Condo",
  "type": "Residential",
  "address": "102 Heaven St.",
  "address2": "",
  "city": "Calgary",
  "region": "Alberta",
  "postalCode": "A989B3",
  "country": "Canada",
  "phone": "9876543214"
}